### ISSUE TITLE
Bug when running posh_nursery.py

### ISSUE THREAD

**Issue by Madiuk** [xzhou13/PoshmarkNursery#1]
sudo python3 posh_nursery.py
Traceback (most recent call last):
  File "/home/pi/PoshmarkNursery/posh_nursery.py", line 562, in <module>
    posh_nursery = Posh_Nursery(username, password, slowMode, debug, checkCaptcha, toShareClosetsFromFile, timeToWait, maintainOrderBasedOnOrderFile, shareBack)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/PoshmarkNursery/posh_nursery.py", line 61, in __init__
    self.driver.minimize_window()
    ^^^^^^^^^^^
AttributeError: 'Posh_Nursery' object has no attribute 'driver'

**Comment by Madiuk** [comment]
Ignore
